version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker
      - run: docker-compose build testserver
      - run: docker-compose run testserver pytest server/tests/
